[package]
name = "io_uring_rt"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
io-uring = "0.7.4"
parking_lot = "0.12.3"
pin-project = "1.1.10"
tokio = { version = "1.44.1", features = ["full"] }
